import { ProductDto } from 'src/dtos/product.dto';
export const products: ProductDto[] = [
  // Productos ya listados (15 primeros)
  {
    name: 'Vela Solar',
    price: 350,
    stock: 15,
    subCategory: 'Velas',
    brand: 'SolarWave',
    description: 'To y la velocidad. Duradera y de alto rendimiento.',
    color: ['azul', 'blanco'],
    material: ['Carbono'],
    size: ['M', 'L', 'XL'],
    measurement: ['5m', '6m', '7m'],
    views: 0,
    category: 'Windsurf',
  },
  {
    name: 'Mástil Pro Carbon',
    price: 200,
    stock: 20,
    subCategory: 'Mastiles',
    brand: 'WindMaster',
    description:
      'Mástil de alta resistencia con materiales avanzados para rendimiento óptimo.',
    color: ['negro'],
    material: ['Carbono', 'Fibra de vidrio'],
    size: ['L'],
    measurement: ['2m', '2.5m'],
    views: 0,
    category: 'Windsurf',
  },
  {
    name: 'Botavara WingFit',
    price: 150,
    stock: 10,
    subCategory: 'Botavaras',
    brand: 'AeroGear',
    description:
      'Botavara ligera y ergonómica para mayor comodidad en el agua.',
    color: ['gris', 'negro'],
    material: ['Aluminio'],
    size: ['S', 'M'],
    measurement: ['1.2m', '1.5m'],
    views: 0,
    category: 'Windsurf',
  },
  {
    name: 'Tabla Freestyle',
    price: 450,
    stock: 5,
    subCategory: 'Tablas',
    brand: 'WaveRider',
    description: 'Tabla diseñada para los trucos más audaces en el agua.',
    color: ['rojo', 'blanco'],
    material: ['Fibra de vidrio'],
    size: ['M', 'L'],
    measurement: ['100cm', '120cm'],
    views: 0,
    category: 'Windsurf',
  },
  {
    name: 'Estrella de Apoyo',
    price: 70,
    stock: 25,
    subCategory: 'Estrellas',
    brand: 'SupportPlus',
    description: 'Estrella robusta para estabilizar el mástil en todo momento.',
    color: ['plateado'],
    material: ['Acero inoxidable'],
    size: ['Universal'],
    measurement: ['30cm'],
    views: 0,
    category: 'Windsurf',
  },
  {
    name: 'Extensor MaxPro',
    price: 120,
    stock: 18,
    subCategory: 'Extensores',
    brand: 'ExtendGear',
    description: 'Extensor ajustable con mecanismo de bloqueo rápido.',
    color: ['negro'],
    material: ['Aluminio'],
    size: ['M'],
    measurement: ['30cm', '40cm'],
    views: 0,
    category: 'Windsurf',
  },
  {
    name: 'Foil Completo Race',
    price: 1200,
    stock: 3,
    subCategory: 'Foil completos',
    brand: 'SpeedFoil',
    description: 'Foil de alta gama para máxima velocidad y estabilidad.',
    color: ['negro', 'dorado'],
    material: ['Carbono', 'Titanio'],
    size: ['XL'],
    measurement: ['100cm'],
    views: 0,
    category: 'Foil',
  },
  {
    name: 'Mástil Foil Xtreme',
    price: 600,
    stock: 7,
    subCategory: 'Mastiles y fuselajes',
    brand: 'FoilEdge',
    description: 'Mástil ultraligero diseñado para maniobras precisas.',
    color: ['azul'],
    material: ['Carbono'],
    size: ['L'],
    measurement: ['1.2m'],
    views: 0,
    category: 'Foil',
  },
  {
    name: 'Ala de Elevación',
    price: 300,
    stock: 10,
    subCategory: 'Alas',
    brand: 'LiftWing',
    description:
      'Ala diseñada para maximizar la sustentación en cada deslizamiento.',
    color: ['blanco', 'negro'],
    material: ['Fibra de carbono'],
    size: ['M'],
    measurement: ['80cm'],
    views: 0,
    category: 'Foil',
  },
  {
    name: 'Repuesto Universal Foil',
    price: 50,
    stock: 50,
    subCategory: 'Accesorios y repuestos',
    brand: 'PartsPro',
    description: 'Repuesto universal compatible con la mayoría de los foils.',
    color: ['negro'],
    material: ['Acero inoxidable'],
    size: ['S', 'M', 'L'],
    measurement: ['10cm', '20cm'],
    views: 0,
    category: 'Foil',
  },
  {
    name: 'Wing Freeride',
    price: 800,
    stock: 5,
    subCategory: 'Wings',
    brand: 'AirGlide',
    description: 'Wing versátil ideal para freeride y olas pequeñas.',
    color: ['verde', 'negro'],
    material: ['Nylon', 'Fibra de carbono'],
    size: ['L'],
    measurement: ['4m', '5m'],
    views: 0,
    category: 'Wing foil',
  },
  {
    name: 'Tabla Compact',
    price: 700,
    stock: 8,
    subCategory: 'Tablas',
    brand: 'CompactFoil',
    description: 'Tabla compacta ideal para maniobras rápidas y precisas.',
    color: ['amarillo', 'azul'],
    material: ['Fibra de vidrio'],
    size: ['M'],
    measurement: ['80cm', '100cm'],
    views: 0,
    category: 'Wing foil',
  },
  {
    name: 'Boomstrap Ajustable',
    price: 90,
    stock: 30,
    subCategory: 'Boomstraps',
    brand: 'WingStrap',
    description: 'Correas ajustables para fijar tu wing con máxima comodidad.',
    color: ['negro'],
    material: ['Nylon'],
    size: ['Universal'],
    measurement: ['30cm'],
    views: 0,
    category: 'Wing foil',
  },
  {
    name: 'Repuestos Wing',
    price: 40,
    stock: 40,
    subCategory: 'Accesorios y repuestos',
    brand: 'RepairKit',
    description:
      'Kit de repuestos esenciales para mantener tu wing en perfectas condiciones.',
    color: ['negro', 'gris'],
    material: ['Plástico', 'Metal'],
    size: ['S'],
    measurement: ['15cm'],
    views: 0,
    category: 'Wing foil',
  },
  // Nuevos productos (16-30)
  {
    name: 'Vela SpeedMaster',
    price: 400,
    stock: 12,
    subCategory: 'Velas',
    brand: 'SpeedWind',
    description: 'Una vela con diseño aerodinámico para máxima velocidad.',
    color: ['rojo', 'amarillo'],
    material: ['Nylon'],
    size: ['M', 'L'],
    measurement: ['5m', '6.5m'],
    views: 0,
    category: 'Windsurf',
  },
  {
    name: 'Foil Pro Racing',
    price: 1500,
    stock: 2,
    subCategory: 'Foil completos',
    brand: 'EliteRide',
    description: 'El foil perfecto para los competidores más exigentes.',
    color: ['negro', 'plateado'],
    material: ['Fibra de carbono'],
    size: ['XL'],
    measurement: ['90cm'],
    views: 0,
    category: 'Foil',
  },
  {
    name: 'Velas HighPerformance',
    price: 480,
    stock: 8,
    subCategory: 'Velas',
    brand: 'WindX',
    description:
      'Velas con diseño avanzado para optimizar velocidad y estabilidad en cualquier condición de viento.',
    color: ['azul', 'negro'],
    material: ['Poliéster reforzado'],
    size: ['L', 'XL'],
    measurement: ['5.5m', '7m'],
    views: 0,
    category: 'Windsurf',
  },
  {
    name: 'Mástil AeroLite',
    price: 180,
    stock: 15,
    subCategory: 'Mastiles',
    brand: 'LiteRide',
    description:
      'Mástil ultraligero con alta resistencia, ideal para maniobras rápidas.',
    color: ['negro', 'gris'],
    material: ['Aluminio', 'Fibra de vidrio'],
    size: ['M'],
    measurement: ['1.8m', '2.1m'],
    views: 0,
    category: 'Windsurf',
  },
  {
    name: 'Botavara UltraFlex',
    price: 200,
    stock: 10,
    subCategory: 'Botavaras',
    brand: 'FlexGear',
    description:
      'Botavara ergonómica que mejora el control en condiciones adversas.',
    color: ['negro', 'rojo'],
    material: ['Aluminio reforzado'],
    size: ['L'],
    measurement: ['1.5m', '1.8m'],
    views: 0,
    category: 'Windsurf',
  },
  {
    name: 'Tabla WindCruise',
    price: 500,
    stock: 6,
    subCategory: 'Tablas',
    brand: 'OceanSurf',
    description: 'Tabla versátil ideal para principiantes y avanzados.',
    color: ['verde', 'blanco'],
    material: ['Fibra de vidrio', 'Espuma de alta densidad'],
    size: ['XL'],
    measurement: ['120cm', '140cm'],
    views: 0,
    category: 'Windsurf',
  },
  {
    name: 'Kit Extensor Adjustable',
    price: 90,
    stock: 22,
    subCategory: 'Extensores',
    brand: 'AdjustoKit',
    description:
      'Kit de extensores ajustables que se adaptan a varias medidas de mástiles.',
    color: ['negro', 'gris'],
    material: ['Acero inoxidable'],
    size: ['S', 'M', 'L'],
    measurement: ['20cm', '30cm', '40cm'],
    views: 0,
    category: 'Windsurf',
  },
  {
    name: 'Foil Explorer',
    price: 1100,
    stock: 5,
    subCategory: 'Foil completos',
    brand: 'HydroFoil',
    description:
      'Foil ideal para quienes buscan explorar nuevas velocidades sobre el agua.',
    color: ['blanco', 'plateado'],
    material: ['Carbono', 'Fibra de vidrio'],
    size: ['L'],
    measurement: ['90cm', '100cm'],
    views: 0,
    category: 'Foil',
  },
  {
    name: 'Ala de Control Avanzado',
    price: 320,
    stock: 12,
    subCategory: 'Alas',
    brand: 'ControlWing',
    description: 'Ala diseñada para un control óptimo y deslizamiento suave.',
    color: ['negro', 'amarillo'],
    material: ['Fibra de carbono'],
    size: ['M', 'L'],
    measurement: ['80cm', '100cm'],
    views: 0,
    category: 'Foil',
  },
  {
    name: 'Wing AirMaster',
    price: 750,
    stock: 7,
    subCategory: 'Wings',
    brand: 'SkySurf',
    description:
      'Wing premium con tecnología avanzada para vuelos más prolongados.',
    color: ['naranja', 'negro'],
    material: ['Nylon reforzado'],
    size: ['M'],
    measurement: ['4.5m', '5m'],
    views: 0,
    category: 'Wing foil',
  },
  {
    name: 'Tabla CompactStyle',
    price: 650,
    stock: 10,
    subCategory: 'Tablas',
    brand: 'CompactRide',
    description:
      'Tabla compacta diseñada para riders que buscan maniobras rápidas.',
    color: ['amarillo', 'negro'],
    material: ['Fibra de carbono'],
    size: ['S', 'M'],
    measurement: ['90cm', '100cm'],
    views: 0,
    category: 'Wing foil',
  },
  {
    name: 'Boomstrap Pro',
    price: 120,
    stock: 18,
    subCategory: 'Boomstraps',
    brand: 'ProStrap',
    description:
      'Boomstrap diseñado para mayor durabilidad y facilidad de uso.',
    color: ['negro', 'azul'],
    material: ['Nylon'],
    size: ['Universal'],
    measurement: ['25cm', '35cm'],
    views: 0,
    category: 'Wing foil',
  },
  {
    name: 'Vela ProRace',
    price: 500,
    stock: 7,
    subCategory: 'Velas',
    brand: 'SpeedWind',
    description:
      'Vela profesional optimizada para carreras con máxima estabilidad.',
    color: ['rojo', 'blanco'],
    material: ['Kevlar', 'Poliéster'],
    size: ['XL'],
    measurement: ['7m', '8.5m'],
    views: 0,
    category: 'Windsurf',
    discount: 10,
  },
  {
    name: 'Mástil CarbonMax',
    price: 300,
    stock: 12,
    subCategory: 'Mastiles',
    brand: 'CarbonTech',
    description:
      'Mástil con 100% fibra de carbono para una resistencia superior.',
    color: ['negro'],
    material: ['Carbono'],
    size: ['L'],
    measurement: ['2.2m', '2.5m'],
    views: 0,
    category: 'Windsurf',
    discount: 15,
  },
  {
    name: 'Botavara ErgoGrip',
    price: 250,
    stock: 9,
    subCategory: 'Botavaras',
    brand: 'ErgoRide',
    description:
      'Diseño ergonómico que mejora el control durante largas sesiones.',
    color: ['gris', 'negro'],
    material: ['Aluminio reforzado'],
    size: ['M'],
    measurement: ['1.6m', '1.9m'],
    views: 0,
    category: 'Windsurf',
    discount: 5,
  },
  {
    name: 'Tabla OceanRider',
    price: 550,
    stock: 4,
    subCategory: 'Tablas',
    brand: 'WaveGear',
    description: 'Tabla ligera y resistente, perfecta para riders avanzados.',
    color: ['azul', 'blanco'],
    material: ['Fibra de vidrio', 'PVC'],
    size: ['L'],
    measurement: ['130cm', '150cm'],
    views: 0,
    category: 'Windsurf',
    discount: 20,
  },
  {
    name: 'Extensor QuickAdjust',
    price: 80,
    stock: 18,
    subCategory: 'Extensores',
    brand: 'AdjustEasy',
    description: 'Extensor ajustable con sistema de bloqueo rápido.',
    color: ['negro', 'plateado'],
    material: ['Acero'],
    size: ['Universal'],
    measurement: ['25cm', '35cm'],
    views: 0,
    category: 'Windsurf',
    discount: 8,
  },
  {
    name: 'Foil SpeedMaster',
    price: 1200,
    stock: 3,
    subCategory: 'Foil completos',
    brand: 'HydroSwift',
    description:
      'Foil diseñado para alcanzar velocidades máximas con estabilidad.',
    color: ['plateado', 'negro'],
    material: ['Carbono', 'Aluminio'],
    size: ['XL'],
    measurement: ['110cm', '120cm'],
    views: 0,
    category: 'Foil',
    discount: 25,
  },
  {
    name: 'Mástil HydraCore',
    price: 220,
    stock: 11,
    subCategory: 'Mastiles y fuselajes',
    brand: 'CoreTech',
    description:
      'Mástil y fuselaje reforzados para mayor durabilidad en condiciones extremas.',
    color: ['gris', 'azul'],
    material: ['Fibra de carbono'],
    size: ['L'],
    measurement: ['2.3m'],
    views: 0,
    category: 'Foil',
    discount: 12,
  },
  {
    name: 'Ala PowerFlow',
    price: 400,
    stock: 6,
    subCategory: 'Alas',
    brand: 'FlowRider',
    description: 'Ala aerodinámica diseñada para máxima eficiencia.',
    color: ['rojo', 'negro'],
    material: ['Fibra de carbono'],
    size: ['M'],
    measurement: ['85cm', '95cm'],
    views: 0,
    category: 'Foil',
    discount: 18,
  },
  {
    name: 'Wing GlideX',
    price: 780,
    stock: 5,
    subCategory: 'Wings',
    brand: 'GlidePro',
    description: 'Wing con diseño avanzado para vuelos suaves y controlados.',
    color: ['amarillo', 'negro'],
    material: ['Nylon'],
    size: ['L'],
    measurement: ['5m', '6m'],
    views: 0,
    category: 'Wing foil',
    discount: 10,
  },
  {
    name: 'Tabla SkyWave',
    price: 700,
    stock: 7,
    subCategory: 'Tablas',
    brand: 'SkyBoard',
    description:
      'Tabla versátil y ligera, diseñada para un rendimiento excepcional.',
    color: ['naranja', 'blanco'],
    material: ['Fibra de vidrio', 'Carbono'],
    size: ['M', 'L'],
    measurement: ['95cm', '110cm'],
    views: 0,
    category: 'Wing foil',
    discount: 20,
  },
  {
    name: 'Boomstrap FlexiLock',
    price: 140,
    stock: 16,
    subCategory: 'Boomstraps',
    brand: 'FlexiGear',
    description: 'Boomstrap resistente con sistema de bloqueo ajustable.',
    color: ['negro', 'gris'],
    material: ['Nylon reforzado'],
    size: ['Universal'],
    measurement: ['30cm', '40cm'],
    views: 0,
    category: 'Wing foil',
    discount: 7,
  },
  {
    name: 'Kit de Reparación QuickFix',
    price: 50,
    stock: 25,
    subCategory: 'Accesorios y repuestos',
    brand: 'RepairKit',
    description: 'Kit completo para reparar velas y tablas rápidamente.',
    color: ['negro', 'rojo'],
    material: ['Plástico', 'Cinta adhesiva'],
    size: ['Compacto'],
    measurement: ['10cm x 15cm'],
    views: 0,
    category: 'Windsurf',
    discount: 5,
  },
  {
    name: 'Foil Combo Performance',
    price: 1350,
    stock: 3,
    subCategory: 'Foil completos',
    brand: 'PerfomancePro',
    description:
      'Set completo de foil diseñado para optimizar tu experiencia sobre el agua.',
    color: ['plateado', 'azul'],
    material: ['Carbono'],
    size: ['XL'],
    measurement: ['115cm'],
    views: 0,
    category: 'Foil',
    discount: 22,
  },
  {
    name: 'Ala WingBlade',
    price: 370,
    stock: 8,
    subCategory: 'Alas',
    brand: 'BladeTech',
    description: 'Ala con diseño estilizado que mejora la maniobrabilidad.',
    color: ['verde', 'negro'],
    material: ['Fibra de carbono'],
    size: ['S', 'M'],
    measurement: ['80cm', '90cm'],
    views: 0,
    category: 'Foil',
    discount: 10,
  },
  {
    name: 'Extensor SteelForce',
    price: 100,
    stock: 20,
    subCategory: 'Extensores',
    brand: 'SteelLine',
    description:
      'Extensor fabricado con acero inoxidable para máxima durabilidad.',
    color: ['plateado', 'negro'],
    material: ['Acero inoxidable'],
    size: ['Universal'],
    measurement: ['30cm', '40cm'],
    views: 0,
    category: 'Windsurf',
    discount: 9,
  },
];
